
import Head from "next/head";
import styles from "../styles/Home.module.css";
import PhoneAuth from 'components/PhoneAuth'

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Auth</a>
        </h1>

        <div className={styles.grid}>
          <PhoneAuth/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="twitter.com/xerosanyam"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by @xerosanyam
        </a>
      </footer>
    </div>
  );
}
